version: "3.3"

services:
  db:
    build: db
    image: pierrelegrandpro/cloud-native-db:1.0.0

  words:
    build: words
    image: pierrelegrandpro/cloud-native-api:1.0.0
    deploy:
      replicas: 5

  web:
    build: web
    image: pierrelegrandpro/cloud-native-web:1.0.0
    ports:
      - "8080:80"