name: Build and Push

on:
  push:
    branches:
      - 'main'
    paths:
      - 'words/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push web
        uses: docker/build-push-action@v3
        with:
          context: words
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloud-native-api:latest
          file: "words/Dockerfile"